### PR TITLE
My contributions to #30

### PR DESCRIPTION
**Pull request by bassosimone**
xref: #31

### CODE REVIEW

**Comment by hellais** [comment]
I think the imports are missing

**Comment by hellais** [comment]
I will add them in merge.

Thanks!

**Comment by bassosimone** [comment]
Oh, sorry, I guess I missed this part:

> Check if FormattedMessage is being imported. If it's not add the line:
>> ```javascript
>> import { FormattedMessage } from 'react-intl'
>> ```

**Comment by hellais** [comment]
It seems like you also used `defaultValue` instead of `defaultMessage`.

**Pull request merged**
